#!/bin/bash
#
# msolver - by: edu@bodhi

[ ! -d ~/.local/share/voice2json/en-us_kaldi-rhasspy ]&&~/.msolver/v2j -p en-us_kaldi-rhasspy download-profile&&echo "[Numbers]
0..9 0..9 0..9 0..9 0..9 0..9 0..9">~/.local/share/voice2json/en-us_kaldi-rhasspy/sentences.ini&&~/.msolver/v2j -p en-us_kaldi-rhasspy train-profile

~/.msolver/v2j -p en-us_kaldi-rhasspy transcribe-wav ./Downloads/audio_verification_challenge_*.wav|~/.msolver/v2j -p en-us_kaldi-rhasspy recognize-intent|jq -r .text
rm ~/Downloads/audio_verification_challenge_*.wav 2>/dev/null
